name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: do-something
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        if: github.event.client_payload.text==''
        run: echo tom ingen text.
      - name: Do Something my
        run: 'echo "Event text: ${{ github.event.client_payload.text }}"'
